#!/usr/bin/env python
"""
VibeVoice-ASR Fine-tuning Example Script

A beginner-friendly wrapper around lora_finetune.py with documented
defaults, synthetic toy dataset generation, and end-to-end inference demo.

Usage:
    # Step 1: Generate toy dataset
    python finetune_example.py --generate_toy_data --toy_output ./toy_example

    # Step 2: Fine-tune
    torchrun --nproc_per_node=1 finetune_example.py \
        --model_path microsoft/VibeVoice-ASR \
        --data_dir ./toy_example \
        --output_dir ./output_example

    # Step 3: Transcribe with fine-tuned model
    python finetune_example.py \
        --inference \
        --base_model microsoft/VibeVoice-ASR \
        --lora_path ./output_example \
        --audio_file ./toy_example/0.mp3 \
        --context_info "Tea Brew, Aiden Host"

Requirements:
    pip install -e . peft transformers torch torchaudio
"""

import argparse
import json
import random
import subprocess
import sys
import uuid
from pathlib import Path


# ─── Step 1: Generate a synthetic toy dataset ─────────────────────────────────

TOY_TEMPLATES = [
    ("Hey everyone, welcome back to the show.", "Thanks for having me. Today we're discussing AI."),
    ("So what got you interested in machine learning?", "I was fascinated by how computers can understand language."),
    ("Can you explain what fine-tuning actually does?", "It adapts a pre-trained model to your specific data and task."),
    ("What's the most important thing when preparing training data?", "Accuracy of transcriptions and consistent speaker labels."),
    ("How long does training typically take?", "A few hours on a single A100 GPU for a small dataset."),
    ("What is customized context used for?", "It lets you inject domain-specific terms and names to boost recognition."),
]

SYNTHETIC_SPEAKERS = [
    "Aiden Host",
    "Dr. Sarah Chen",
    "Marcus Williams",
    "Priya Patel",
    "Tea Brew",
    "The Property is near Meter Street.",
]


def generate_toy_dataset(output_dir: Path, num_samples: int = 10) -> None:
    """Generate a synthetic toy dataset for demonstration."""
    output_dir.mkdir(parents=True, exist_ok=True)

    audio_note = output_dir / "NOTE.txt"
    audio_note.write_text(
        "This is synthetic data generated by finetune_example.py for demonstration.\n"
        "For real fine-tuning, replace these files with real audio and transcriptions.\n"
    )

    for i in range(num_samples):
        seg_a, seg_b = random.sample(TOY_TEMPLATES, 2)
        speaker_a, speaker_b = random.sample(SYNTHETIC_SPEAKERS, 2)

        start_a = 0.0
        end_a = float(len(seg_a) / 10)  # ~chars/10 seconds
        start_b = end_a + 0.5
        end_b = start_b + float(len(seg_b) / 10)

        duration = end_b + 5.0

        label = {
            "audio_duration": duration,
            "audio_path": f"{i}.mp3",
            "segments": [
                {"speaker": 0, "text": seg_a, "start": start_a, "end": end_a},
                {"speaker": 1, "text": seg_b, "start": start_b, "end": end_b},
            ],
            "customized_context": [speaker_a, speaker_b],
        }

        (output_dir / f"{i}.json").write_text(json.dumps(label, indent=2))
        # Placeholder audio — replace with real .mp3 files for actual training
        # (output_dir / f"{i}.mp3").write_bytes(b"")

    print(f"Generated {num_samples} sample labels in {output_dir}/")
    print("NOTE: .mp3 files are placeholders. Replace with real audio for actual training.")
    print(f"\nNext: torchrun --nproc_per_node=1 finetune_example.py --model_path microsoft/VibeVoice-ASR "
          f"--data_dir {output_dir} --output_dir ./output_example\n")


# ─── Step 2: Delegate to lora_finetune.py ─────────────────────────────────────

def run_finetuning() -> None:
    """Delegate to lora_finetune.py with the same arguments (minus --generate_toy_data)."""
    our_args = sys.argv[1:]
    real_script = Path(__file__).parent / "lora_finetune.py"

    cmd = ["torchrun", "--nproc_per_node=1", str(real_script)] + our_args
    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd)
    sys.exit(result.returncode)


# ─── Step 3: Run inference with fine-tuned model ───────────────────────────────

def run_inference(args: argparse.Namespace) -> None:
    """Run transcription using a LoRA fine-tuned model."""
    try:
        from peft import PeftModel
        import torch
        from vibevoice.modular.modeling_vibevoice_asr import VibeVoiceASRForConditionalGeneration
        from vibevoice.processor.vibevoice_asr_processor import VibeVoiceASRProcessor
    except ImportError as e:
        sys.exit(f"Missing dependencies. Run: pip install peft transformers torch torchaudio\n{e}")

    print(f"Loading base model: {args.base_model}")
    processor = VibeVoiceASRProcessor.from_pretrained(
        args.base_model,
        language_model_pretrained_name="Qwen/Qwen2.5-7B"
    )
    model = VibeVoiceASRForConditionalGeneration.from_pretrained(
        args.base_model,
        dtype=torch.bfloat16,
        device_map="auto",
        attn_implementation="flash_attention_2",
        trust_remote_code=True,
    )

    print(f"Loading LoRA adapter: {args.lora_path}")
    model = PeftModel.from_pretrained(model, args.lora_path)
    model.eval()

    audio_file = Path(args.audio_file)
    if not audio_file.exists():
        sys.exit(f"Audio file not found: {audio_file}")

    print(f"Transcribing: {audio_file}")
    # Dynamically import so inference_lora is not a hard dependency
    sys.path.insert(0, str(Path(__file__).parent))
    # Reuse the transcription logic from inference_lora.py
    from inference_lora import transcribe as _transcribe
    result = _transcribe(
        model, processor, str(audio_file),
        max_new_tokens=4096, temperature=0.0,
        context_info=getattr(args, "context_info", None),
    )
    print("\n=== Transcription ===")
    print(json.dumps(result, indent=2))


# ─── CLI ───────────────────────────────────────────────────────────────────────

def parse_args():
    parser = argparse.ArgumentParser(description="VibeVoice-ASR Fine-tuning Example")
    parser.add_argument("--generate_toy_data", action="store_true",
                        help="Generate a synthetic toy dataset")
    parser.add_argument("--toy_output", type=Path, default=Path("./toy_example"),
                        help="Output directory for toy dataset")
    parser.add_argument("--num_toy_samples", type=int, default=10,
                        help="Number of toy samples to generate")
    parser.add_argument("--inference", action="store_true",
                        help="Run inference with a fine-tuned model")
    parser.add_argument("--base_model", type=str, default="microsoft/VibeVoice-ASR")
    parser.add_argument("--lora_path", type=str, default="./output")
    parser.add_argument("--audio_file", type=str)
    parser.add_argument("--context_info", type=str, default=None)
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()

    if args.generate_toy_data:
        generate_toy_dataset(args.toy_output, args.num_toy_samples)
    elif args.inference:
        run_inference(args)
    else:
        # Delegate fine-tuning to the real script
        run_finetuning()
